### ISSUE TITLE
Does ambit support all monogram module, need a driver?

### ISSUE THREAD

**Issue by eric-lmi** [khimaros/ambit#1]
Hi

plaining to use monogram on linux. does it just connect to linux as a standard midi device? don't need a driver? so ambit is a project to offer customization of monogram in software?

**Comment by khimaros** [comment]
hi @eric-lmi -- you shouldn't need any special drivers. the PaletteGear and MonogramCC both expose standard USB profiles including bulk, MIDI, and HID. the instructions in the README should get you up and running.

i personally have tested only the predecessor (PaletteGear) devices with ambit. there may be small differences to account for and i would be happy to help you get the MonogramCC up and running if you run into problems.

please try to follow the documentation and let me know if anything doesn't work as documented. please include as much information as possible including reproduction steps.

**Comment by khimaros** [comment]
it turns out quite a bit of work is required to support these.

i'll be tracking here: https://github.com/khimaros/ambit/issues/2
